"""Evaluation, reporting, and rejection-threshold utilities."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score
from torch.utils.data import DataLoader


@dataclass(frozen=True)
class EvaluationResult:
    """Evaluation outputs for one split.

    Attributes:
        loss: Mean loss over all samples.
        accuracy: Multiclass accuracy without rejection.
        macro_f1: Macro F1 without rejection.
        y_true: Ground-truth labels.
        y_pred: Predicted labels.
        max_probs: Maximum softmax probability for each sample.
        probabilities: Full softmax probability matrix.
    """

    loss: float
    accuracy: float
    macro_f1: float
    y_true: np.ndarray
    y_pred: np.ndarray
    max_probs: np.ndarray
    probabilities: np.ndarray


def evaluate_model(
    model: nn.Module,
    loader: DataLoader,
    criterion: nn.Module,
    device: torch.device,
) -> EvaluationResult:
    """Evaluate a classifier and collect probabilities.

    Args:
        model: Classifier to evaluate.
        loader: DataLoader for the evaluated split.
        criterion: Loss function.
        device: Device used for inference.

    Returns:
        Evaluation metrics and raw predictions.
    """
    model.eval()
    total_loss = 0.0
    y_true_batches: list[np.ndarray] = []
    y_pred_batches: list[np.ndarray] = []
    prob_batches: list[np.ndarray] = []

    with torch.no_grad():
        for images, targets in loader:
            images = images.to(device)
            targets = targets.to(device)
            logits = model(images)
            loss = criterion(logits, targets)
            probabilities = torch.softmax(logits, dim=1)
            predictions = probabilities.argmax(dim=1)

            batch_size = targets.size(0)
            total_loss += loss.item() * batch_size
            y_true_batches.append(targets.cpu().numpy())
            y_pred_batches.append(predictions.cpu().numpy())
            prob_batches.append(probabilities.cpu().numpy())

    y_true = np.concatenate(y_true_batches)
    y_pred = np.concatenate(y_pred_batches)
    probabilities = np.concatenate(prob_batches)
    max_probs = probabilities.max(axis=1)
    mean_loss = total_loss / max(1, len(y_true))
    return EvaluationResult(
        loss=float(mean_loss),
        accuracy=float(accuracy_score(y_true, y_pred)),
        macro_f1=float(f1_score(y_true, y_pred, average="macro", zero_division=0)),
        y_true=y_true,
        y_pred=y_pred,
        max_probs=max_probs,
        probabilities=probabilities,
    )


def choose_rejection_threshold(max_probs: np.ndarray, percentile: float = 5.0) -> float:
    """Choose a confidence threshold from validation max probabilities.

    Args:
        max_probs: Maximum softmax probabilities from the validation split.
        percentile: Percentile used as the rejection threshold.

    Returns:
        Confidence threshold. Predictions below it should be returned as ``outros``.
    """
    clipped_percentile = min(max(percentile, 0.0), 100.0)
    return float(np.percentile(max_probs, clipped_percentile))


def classification_report_frame(
    y_true: np.ndarray,
    y_pred: np.ndarray,
    class_names: list[str],
) -> pd.DataFrame:
    """Build a classification report DataFrame.

    Args:
        y_true: Ground-truth labels.
        y_pred: Predicted labels.
        class_names: Class names in label-index order.

    Returns:
        Report generated by scikit-learn.
    """
    report = classification_report(
        y_true,
        y_pred,
        target_names=class_names,
        labels=list(range(len(class_names))),
        output_dict=True,
        zero_division=0,
    )
    return pd.DataFrame(report).transpose()


def save_confusion_matrix(
    y_true: np.ndarray,
    y_pred: np.ndarray,
    class_names: list[str],
    output_png: Path,
    output_csv: Path,
) -> None:
    """Save confusion matrix as CSV and PNG.

    Args:
        y_true: Ground-truth labels.
        y_pred: Predicted labels.
        class_names: Class names in label-index order.
        output_png: Destination image file.
        output_csv: Destination CSV file.
    """
    matrix = confusion_matrix(y_true, y_pred, labels=list(range(len(class_names))))
    frame = pd.DataFrame(matrix, index=class_names, columns=class_names)
    output_png.parent.mkdir(parents=True, exist_ok=True)
    output_csv.parent.mkdir(parents=True, exist_ok=True)
    frame.to_csv(output_csv)

    fig, ax = plt.subplots(figsize=(8, 6))
    image = ax.imshow(matrix, cmap="Blues")
    ax.set_xticks(np.arange(len(class_names)), labels=class_names, rotation=45, ha="right")
    ax.set_yticks(np.arange(len(class_names)), labels=class_names)
    ax.set_xlabel("Predito")
    ax.set_ylabel("Real")
    ax.set_title("Matriz de confusao")
    for row_index in range(matrix.shape[0]):
        for col_index in range(matrix.shape[1]):
            ax.text(col_index, row_index, matrix[row_index, col_index], ha="center", va="center")
    fig.colorbar(image, ax=ax, fraction=0.046, pad=0.04)
    fig.tight_layout()
    fig.savefig(output_png, dpi=160)
    plt.close(fig)


def save_confidence_analysis(
    result: EvaluationResult,
    threshold: float,
    class_names: list[str],
    output_path: Path,
) -> dict[str, float]:
    """Save per-sample confidence and rejection analysis.

    Args:
        result: Evaluation result for validation or test data.
        threshold: Confidence threshold used for rejection.
        class_names: Class names in label-index order.
        output_path: Destination CSV path.

    Returns:
        Summary metrics for rejected and accepted samples.
    """
    accepted = result.max_probs >= threshold
    rows = []
    for index, true_label in enumerate(result.y_true):
        predicted_label = result.y_pred[index]
        rows.append(
            {
                "true_label": class_names[int(true_label)],
                "predicted_label": class_names[int(predicted_label)],
                "confidence": float(result.max_probs[index]),
                "accepted": bool(accepted[index]),
                "final_label": class_names[int(predicted_label)] if accepted[index] else "outros",
            }
        )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    pd.DataFrame(rows).to_csv(output_path, index=False)

    accepted_count = int(accepted.sum())
    rejected_count = int((~accepted).sum())
    accepted_accuracy = (
        accuracy_score(result.y_true[accepted], result.y_pred[accepted]) if accepted_count else 0.0
    )
    return {
        "threshold": float(threshold),
        "accepted_count": float(accepted_count),
        "rejected_count": float(rejected_count),
        "rejection_rate": float(rejected_count / max(1, len(result.y_true))),
        "accepted_accuracy": float(accepted_accuracy),
    }
